name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get dependencies
      run: make clean && make image

    - name: Build
      run: make build

    - name: Test
      run: make test
